binary_features:
  from_zeros:
  - Blast Furnace Slag
  - Superplasticizer
competition:
  name: skillbox-ml-junior-regression-10
data:
  logs: logs
  processed_dir: data/processed
  raw_dir: data/raw
  test_file: test.csv
  train_file: train.csv
output:
  eda_report_dir: outputs/eda_report  
models_saving:
  modeling_report_dir: models/modeling_report
  best_pipeline_dir: models/pipelines
processed_files:  
  train_file:
    csv: eda_data_train.csv
    pkl: eda_data_train.pkl
    parquet: eda_data_train.parquet
  test_file:
    csv: eda_data_test.csv
    pkl: eda_data_test.pkl
    parquet: eda_data_test.parquet
abnormal_value:
  sp_c_pct: 0.098
  fine_aggregate: 970
standard_value:
  age:
    max: 365
    min: 1
  cement:
    max: 600
    min: 200
  coarse_aggregate:
    max: 1300
    min: 1000
  fine_aggregate:
    max: 800
    min: 600
  fly_ash:
    max: 200
    min: 0
  sp_c_pct:
    max: 0.025
    min: 0.005
  strength:
    max: 100
    min: 5
  w_c:
    max: 0.7
    min: 0.3
  water:
    max: 220
    min: 120
task_type: regression
trend_settings:
  colors:
  - red
  - blue
  - green
  - orange
  - purple
  names:
  - Linear
  - Log
  - Sqrt
  - 1/x
  - "x\xB2"


optuna:
  direction: "minimize"
  n_trials: 100
  
cross_validation:
  strategy: "RepeatedKFold"
  n_splits: 5
  n_repeats: 5
  random_state: 42

catboost_params:
  search_space:
    iterations:
      type: "suggest_int"
      low: 1000
      high: 3000
    depth:
      type: "suggest_int" 
      low: 4
      high: 10
    learning_rate:
      type: "suggest_float"
      low: 0.01
      high: 0.3
      log: true
    l2_leaf_reg:
      type: "suggest_float"
      low: 1
      high: 10
    random_strength:
      type: "suggest_float"
      low: 0.1
      high: 10
    border_count:
      type: "suggest_int"
      low: 32
      high: 255
    bagging_temperature:
      type: "suggest_float"
      low: 0.0
      high: 1.0
  
  fixed_params:
    verbose: false
    random_state: 42

models:
  catboost:
    param_space: "catboost_params"